[package]
name = "oratio-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
oratio-core = { path = "../oratio-core" }
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
indicatif = "0.17"
hound = "3"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
